/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `java-library`
}

dependencies {
    implementation("org.apache.commons:commons-text:1.13.0")
    api(project(":list"))

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.1")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
