/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.utilities;

import org.example.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }

    public static boolean isBlank(String s) {
        return s == null || s.isBlank();
    }

    public static String reverse(String s) {
      StringBuilder sb = new StringBuilder(s);
      StringBuilder reversed = sb.reverse();
      return reversed.toString();
    }
}
