/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }

    public static String withHighFive(String message) {
        if (message == null) {
            return null;
        }
        message = message.trim();
        return "High Five: " + message;
    }
}
