/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    java
}

dependencies {
    implementation("org.apache.commons:commons-text:1.13.0")
    implementation(project(":utilities"))

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.1")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
